const child_process = require("child_process");
const cdk8s = require('cdk8s');
const fs = require('fs');
const os = require('os');
const path = require('path');
const tfaws = require('@winglang/sdk/lib/target-tf-aws');

exports.shell = async function (command, args, cwd) {
  return new Promise((resolve, reject) => {
    child_process.execFile(command, args, { cwd }, (error, stdout, stderr) => {
      if (error) {
        console.error(stderr);
        return reject(error);
      }

      return resolve(stdout ? stdout : stderr);
    });
  });
};

exports.entrypointDir = function (scope) {
  return scope.node.root.entrypointDir;
};

exports.toHelmChart = function(chart) {
  const app = cdk8s.App.of(chart);
  app.resolvers = [new cdk8s.LazyResolver(), new cdk8s.ImplicitTokenResolver(), new cdk8s.NumberStringUnionResolver()];
  const docs = cdk8s.App._synthChart(chart);

  const workdir = fs.mkdtempSync(path.join(os.tmpdir(), "helm."));
  const templates = fs.mkdirSync(path.join(workdir, "templates"), {recursive: true});

  const yaml = cdk8s.Yaml.stringify(...docs);
  fs.writeFileSync(path.join(templates, "all.yaml"), yaml);

  const manifest = {
    apiVersion: "v2",
    name: "app",
    description: "generated by wing",
    type: "application",
    version: "0.1.0",
    appVersion: "0.1.0",
  };

  fs.writeFileSync(path.join(workdir, "Chart.yaml"), cdk8s.Yaml.stringify(manifest));

  return workdir;
};

exports.awsRegion = function(scope) {
  return tfaws.App.of(scope).region;
}

// exports.awsVpc = function(scope) {
//   return tfaws.App.of(scope).vpc;
// }

// exports.toSubnet = function(scope) {
//   return scope;
// }